### ISSUE TITLE
Uninitialized string offset 0 

### ISSUE THREAD

**Issue by esginmurat** [MyThemeShopTeam/wordpress-helpers#32]
Hello. Thanks for this plugin. 

My system: ubuntu linux 22.04.1
Wordpress version: 6.1.1
Rank Math SEO: 1.0.105
Php: 8.1.x

I am getting the following error in the error logs. AH01071: Got error PHP message: PHP Warning: Uninitialized string offset 0 in seo-by-rank-math/vendor/mythemeshop/wordpress-helpers/src/helpers/class-str.php on line 235

line 235 is here
$ucwords .= preg_match( '/[\p{L}]/u', $word[0] ) ? mb_strtoupper( $word[0], 'UTF-8' ) . mb_substr( $word, 1, mb_strlen( $word ), 'UTF-8' ) : $word;

Thanks in advance for your help.

**Comment by esginmurat** [comment]
The problem persists. Unfortunately, there are thousands of people on the internet who have the same problem. Please create a fix. respects.

My system: ubuntu linux 22.04.2
Wordpress version: 6.2
Rank Math SEO: 1.0.111
Php: 8.1.x

**Comment by pratikrm** [comment]
Closing this issue as we have fixed it in the latest version.
